// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace MVMCorrespondencia.Models
{
    public partial class Contactos
    {
        public Contactos()
        {
            CorrespondeciainternaIdcontactodestinatarioNavigation = new HashSet<Correspondeciainterna>();
            CorrespondeciainternaIdcontactoremitenteNavigation = new HashSet<Correspondeciainterna>();
            CorrespondenciaexternaIdcontactodestinatarioNavigation = new HashSet<Correspondenciaexterna>();
            CorrespondenciaexternaIdcontactoremitenteNavigation = new HashSet<Correspondenciaexterna>();
        }

        public int Idcontacto { get; set; }
        public string Documento { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public int? Celular { get; set; }
        public string Correo { get; set; }

        public virtual ICollection<Correspondeciainterna> CorrespondeciainternaIdcontactodestinatarioNavigation { get; set; }
        public virtual ICollection<Correspondeciainterna> CorrespondeciainternaIdcontactoremitenteNavigation { get; set; }
        public virtual ICollection<Correspondenciaexterna> CorrespondenciaexternaIdcontactodestinatarioNavigation { get; set; }
        public virtual ICollection<Correspondenciaexterna> CorrespondenciaexternaIdcontactoremitenteNavigation { get; set; }
    }
}