// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace MVMCorrespondencia.Models
{
    public partial class Correspondenciaexterna
    {
        public int Consecutivoexterna { get; set; }
        public int? Idcontactoremitente { get; set; }
        public int? Idcontactodestinatario { get; set; }
        public DateTime? Fecha { get; set; }
        public string Radicadoexterno { get; set; }

        public virtual Contactos IdcontactodestinatarioNavigation { get; set; }
        public virtual Contactos IdcontactoremitenteNavigation { get; set; }
    }
}